### ISSUE TITLE
Outdated Patches

### ISSUE THREAD

**Issue by SwimmingLink** [TheFakeMateo/rpp-backup#9]
Pretty low priority/importance here, but I just wanted to point out that the patches are outdated (and the patches in the v4 project seem to be even older). Not really needed to update as we can just build our own, but I'm sure that the patches are a lot of people's go-to as it's quicker/easier.
Also, the v4 repo hosts 2.4.2 patches. That might be cool to host in this repo as well (even if heavily outdated as I don't think you're updating that anymore)

**Comment by JustRegularLuna** [comment]
hmm, the patches should be up-to-date with what I called the last official release, although I did make a small change Absorb and Mega Drain since then. The other changes since the release have been updates to the Readme or making it not throw errors when compiling on modern versions of RGBDS.  Are the IPS patches here not v3.0.2? Because I haven't put out a v3.0.3 yet, which would include the Absorb/Mega Drain tweaks and possibly some other tweaks I haven't made yet.

**Comment by JustRegularLuna** [comment]
You're right about the ones in v4 being very outdated though. I should really just remove the patches folder from that repo for now, since v4 has no stable release yet.

**Comment by SwimmingLink** [comment]
I'm not sure on the fine version number. I don't think the IPS format hosts version number internally. My main clue is the date uploaded. But yeah, that Absorb & Mega Drain was definitely not included.

**Comment by JustRegularLuna** [comment]
The date uploaded is consistent with the last official release. And if you start a new game, you will see the precise version number on the little Pikachu screens with the text on them. Please do not report an issue when you have not even confirmed what you are talking about.
